name: through_right_gate__right_00
frame: mocap
fps: 10
total_time_s: 8.0
yaw_mode: tangent
scene: configs/scenes/right_gate.yaml
waypoints:
- name: start
  p:
  - 0.0
  - 0.0
  - 1.5
  yaw: 0.0
  t: 0.0
- name: approach
  p:
  - -0.29474542194172537
  - -0.8319413089761604
  - 1.5
- name: gate
  p:
  - 0.495
  - -1.21
  - 1.5
- name: post_gate
  p:
  - 0.7
  - -1.5
  - 1.4
- name: hover
  p:
  - 1.525
  - -0.615
  - 1.0
  yaw: 0.0
  t: 8.0
velocity_constraints:
  max_speed_mps: 1.5
  max_yaw_rate_rad_s: 1.0
