name: through_left_gate__down_00
frame: mocap
fps: 10
total_time_s: 8.0
yaw_mode: tangent
scene: configs/scenes/left_gate.yaml
waypoints:
- name: start
  p:
  - 0.0
  - 0.0
  - 1.5
  yaw: 0.0
  t: 0.0
- name: approach
  p:
  - 0.45
  - 0.4
  - 1.2950417093414412
- name: gate
  p:
  - 0.915
  - 0.75
  - 1.5
- name: post_gate
  p:
  - 1.75
  - 1.3
  - 1.4
- name: hover
  p:
  - 1.525
  - -0.615
  - 1.0
  t: 8.0
velocity_constraints:
  max_speed_mps: 1.5
  max_yaw_rate_rad_s: 1.0
